app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import db,login_manager
from datetime import datetime
import bleach
from markdown import markdown


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Article(db.Model):
    __tablename__='articles'
    id=db.Column(db.Integer,primary_key=True)
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    title=db.Column(db.String(64),index=True)
    item_id = db.Column(db.Integer, db.ForeignKey('items.id'))
    body_html = db.Column(db.Text)

    @staticmethod
    def on_changed_body(target,value,oldvalue,initiator):
        #需要转换的标签
        allowed_tags=[
            'a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
            'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
            'h1', 'h2', 'h3', 'p', 'img'
        ]
        target.content_html = bleach.linkify(
            bleach.clean(
                markdown(value, output_format='html'),
                tags=allowed_tags,
                strip=True
            )
        )

db.event.listen(Article.body, 'set', Article.on_changed_body)

class Item(db.Model):
    __tablename__='items'
    id=db.Column(db.Integer, primary_key=True)
    tag=db.Column(db.String(64))
    articles = db.relationship('Article', backref='item')

class Like(db.Model):
    __tablename__='likes'
    id=db.Column(db.Integer, primary_key=True)
    like_sum=db.Column(db.Integer)

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, BooleanField, SelectField,\
    SubmitField,HiddenField
from wtforms.validators import Required, Length, Email, Regexp,DataRequired
from wtforms import ValidationError
from flask_pagedown.fields import PageDownField
from ..models import User
from flask_wtf.file import FileField

class PostForm(Form):
    body = TextAreaField("What's on your mind?", validators=[Required()])
    submit = SubmitField('Submit')

class ArticleForm(Form):
    title = StringField('标题', validators=[Required()])
    body = PageDownField('正文', validators=[Required()])
    tag  = StringField('标签',validators=[Required()])
    submit = SubmitField('发布文章')

class UploadForm(Form):
    file=FileField()
    submit = SubmitField('上传文件') 

app/__init__.py
from flask import Flask,render_template
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_login import LoginManager
from flask_pagedown import PageDown


bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
pagedown=PageDown()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
#pagedown=PageDown()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)


    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)


    #注册蓝本
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    #注册认证蓝本
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/auth')
    
    return app


    
    

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views,errors

app/main/views.py
import os
from werkzeug import secure_filename
from . import main
from flask import render_template,current_app,request,redirect,url_for,request,current_app,flash,send_from_directory
from flask_login import login_required,current_user
from ..models import User, Article,Item
from .forms import ArticleForm,UploadForm
import time 
from .. import db


@main.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Article.query.order_by(Article.timestamp.desc()).paginate(page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],error_out=False)
    articles = pagination.items
    return render_template('index.html',articles=articles,pagination=pagination)

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/publish',methods=['GET', 'POST'])
def publish():
    form=ArticleForm()
    if form.validate_on_submit():
        tag = Item(tag=form.tag.data)
        article=Article(body=form.body.data,title=form.title.data,item=tag)
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('.index'))
    return render_template('publish.html',form=form)

@main.route('/article/<int:id>')
def article(id):
    article=Article.query.get_or_404(id)
    return render_template('article.html', articles=[article])

@main.route('/item/<tag>',methods=['GET','POST'])
def item(tag):
    vector=[]
    items=Item.query.filter_by(tag=tag).all()
    for item in items:
        vector.append(item.articles[0])
    articles=vector
    articles.reverse()
    return render_template('item.html',articles=articles)

@main.route('/edit/<int:id>',methods=['GET','POST'])
def edit(id):
    article=Article.query.get_or_404(id)
    form=ArticleForm()
    if form.validate_on_submit(): 
        article.title=form.title.data
        article.body=form.body.data
        article.item.tag=form.tag.data
        db.session.add(article)
        db.session.commit()
        flash('主人,文章已修改完毕')
        return redirect(url_for('.article',id=article.id))
    form.body.data=article.body
    form.title.data=article.title
    form.tag.data=article.item.tag
    return render_template('edit_article.html',form=form) 

# 设置允许上传的文件类型
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg','tar','tar.gz'])
UPLOAD_FOLDER = './uploads'
#检查文件类型是否合法
def allowed_file(filename):
    # 判断文件的扩展名是否在配置项ALLOWED_EXTENSIONS中
    return '.' in filename and filename.rsplit('.',1)[1] in ALLOWED_EXTENSIONS

def GetFileList(dir,fileList):
    newDir=dir
    if os.path.isfile(dir):
        file=dir.replace('app/uploads/','')
        print(file)
        fileList.append(file)
    elif os.path.isdir(dir):
        for s in os.listdir(dir):
            newDir=os.path.join(dir,s)
            GetFileList(newDir, fileList)
    return fileList

@main.route('/upload',methods=['GET','POST'])
def upload():
    form=UploadForm()
    if form.validate_on_submit():
        filename = secure_filename(form.file.data.filename)
        if filename and allowed_file(filename):
            form.file.data.save('app/uploads/'+filename)
            return "上传成功"
        else:
            return "上传失败"
    else:
        filelist=GetFileList('app/uploads/', [])
        return render_template('upload.html',form=form,filelist=filelist)

@main.route('/download/<path:filename>',methods=['GET','POST'])
def download(filename):
    return send_from_directory('uploads/',filename, as_attachment=True)
   
 
@main.route('/delete/<int:id>',methods=['GET','POST'])
def delete(id):
    article=Article.query.get_or_404(id)   
    db.session.delete(article)
    db.session.commit()
    flash('删除成功')
    return redirect(url_for('.index'))

#上下文环境变量定义appname
@main.context_processor
def appinfo():
    return dict(appname=current_app.name)

#上下文环境变量定义current_time() or current_time(%Y-%m-%d)
@main.context_processor
def get_current_time():
    def get_time(timeFormat="%b %d, %Y - %H:%M:%S"):
        return time.strftime(timeFormat)
    return dict(current_time=get_time)

app/templates/_articles.html
<ul class="articles">
    {% for article in articles %}
    <li class="article">
        <div class="blog-post">
             <h2 class="blog-post-title">{{ article.title }}</h2>
             
             <p class="blog-post-meta">
                 <a href="/">首页</a>
                 <a href="{{ url_for('.article', id=article.id) }}">查看全文</a>
             </p>
             <!--
             <p class="article-body">
             -->
             <p>
                 {% if article.body_html %}
                     {{ article.body_html |safe }}
                 {% else %}
                     {{ article.body }}
                 {% endif %} 
             </p>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/about.html
{% extends "base.html" %}

{% block title %}印第安酋长资料信息{% endblock %}

{% block page_content %}
<div>
    <img class="img-rounded profile-thumbnail" src="static/qiuzhang.jpg">
    <div class="profile-header">
        <h1>印第安酋长个人信息</h1>
        <p>
            来自 <a href="http://map.baidu.com/?q=Beijing">Beijing</a>
        </p>
        <p>
            软件工程师
        </p>
        <p>
            爱好：编程.足球.游泳.跑步
        </p>
        <p>
            当前时间: {{ current_time() }}
        </p> 
    </div>
</div>
{% endblock %}

app/templates/article.html
{% extends "base.html" %}

{% block title %}article{% endblock %}
{% block page_image %}
    <div class="container-fluid header">
        <div class="row">
            <div class="image_header col-lg-12" style="height: 400px;;background-image: url('http://img.taopic.com/uploads/allimg/120724/201991-120H413434558.jpg')">
            </div>
        </div>
    <div>
{% endblock %}
{% block page_content %}
    <ul class="articles">
    {% for article in articles %}
    <div class="article">
        <div class="article-title">
                <h4 class="article-title">{{ article.title }}</h4>
        </div>

        <div  style="margin-top: 30px;" class="article_body">
            {% if article.body_html %}
                {{ article.body_html | safe }}
            {% else %}
                {{article.body}}
            {% endif %}
        </div>
        <div class="row">
            <a class="article_tag" href="{{ url_for('.item',tag = article.item.tag) }}">
                <span class="label label-info">
                {{ article.item.tag }}
                </span>
            </a>
            {% if current_user.is_authenticated %}
                <a href="{{url_for('.edit',id=article.id)}}">
                    <span class="label label-primary">编辑</span>
                </a>
                <a href="#" onclick="confirmDelete('{{ article.id }}')">
                    <span class="label label-primary">删除</span>
                </a>
            {% endif %}
            <p class="col-lg-3 col-sm-3 col-xs-7 col-xs-offset-5 col-sm-offset-9 col-lg-offset-9 article_time">{{ moment(article.timestamp).format('YYYY-MM-DD HH:mm:ss') }} </p>
        </div>

        <hr />
    <div class="row">
        <div class="ds-thread col-xs-11" data-thread-key="{{ article.id }}" data-title="{{ article.title }}" data-url="/article/{{ article.id }}"></div>
    </div>
</script>
<!-- 多说公共JS代码 end -->
    </div>
    {% endfor %}
</ul>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}印第安酋长{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='qiuzhang.jpg') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='qiuzhang.jpg') }}" type="image/x-icon">
<!--
<link type="text/css" href="http://cdn.bootcss.com/flat-ui/2.2.2/css/flat-ui.css" rel="stylesheet">
<link type="text/css" href="http://cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
-->
<!--
<script type="text/javascript" src="http://cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
<script type="text/javascript" src="http://cdn.bootcss.com/jquery.nicescroll/3.6.8/jquery.nicescroll.min.js"></script>
<script type="text/javascript" src="http://cdn.bootcss.com/headroom/0.7.0/headroom.min.js"></script>
-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">

<link href="http://cdn.bootcss.com/highlight.js/9.2.0/styles/ir-black.min.css" rel="stylesheet">
<script type="text/javascript" src="http://api.youziku.com/webfont/FastJS/yzk_71173B3BF6CF5B88"></script>
{% endblock %}

{% block navbar %}
<!--
<div class="navbar navbar-inverse blog-head" role="navigation">
-->
<div class="blog-head" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--
            <a class="navbar-brand" href="/">Flasky</a>
            -->
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a class="blog-nav-item" href="/">主页</a></li>
                <li><a class="blog-nav-item" href="/about">关于我</a>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a class="blog-nav-item" href="{{ url_for('main.publish') }}">发布文章</a></li>
                <li><a class="blog-nav-item" href="{{ url_for('main.upload') }}">上传文件</a></li>
                <li><a class="blog-nav-item" href="{{ url_for('auth.logout') }}">登出</a></li>
                {% else %}
                <li><a class="blog-nav-item" href="{{ url_for('main.upload') }}">下载文件</a></li>
                <li><a class="blog-nav-item" href="{{ url_for('auth.login') }}">登陆</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block page_content %}{% endblock %}
</div>
<br>
<hr/>
<footer class="blog-footer">
    <p>
        <a href="#">回到顶部</a>
    </p>
</footer>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="//cdn.bootcss.com/bootbox.js/4.4.0/bootbox.min.js"></script>
    <script>
        var $SCRIPT_ROOT = {{request.script_root|tojson|safe}};
    </script>
    <script src="{{ url_for('static', filename='article.js') }}"></script>
{% endblock %}

app/templates/edit_article.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}

{% block title %}编辑{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>编辑文章</h1>
</div>
<div>
{{ wtf.quick_form(form)}}
</div>
<div class="flask-pagedown-preview">

</div>
{% endblock %}
{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}印第安酋长{% endblock %}


{% block page_content %}
<div class="row">
<div class="col-sm-8 articles">
    {% for article in articles%}
    <div class="article">
        <div class="article-title">
            <a href="{{ url_for('.article',id=article.id) }}">
                <h5><!--<span class="glyphicon glyphicon-link"></span>-->{{ article.title }}</h5>
            </a>
        </div>
        <a href="{{ url_for('.article',id=article.id) }}">
            <div class="article_body">
                {% if article.body_html %}
                    {{ article.body_html | safe | truncate(200,  killwords=False, end='...') }}
                {% else %}
                    {{ article.body | safe | truncate(300,killwords=False,end='.......') }}
                {% endif%}
            </div>
        </a>
        <div class="row">
            <a class="article_tag" href="{{ url_for('.item',tag = article.item.tag) }}">
                <span class="label label-info">
                {{ article.item.tag }}
                </span>
            </a>
            {% if current_user.is_authenticated %}
                <a href="{{url_for('.edit',id=article.id)}}">
                    <span class="label label-primary">编辑</span>
                </a>
                <a href="#" onclick="confirmDelete('{{ article.id }}')">
                    <span class="label label-primary">删除</span>
                </a>
            {% endif %}
            <p class="article_time">{{ moment(article.timestamp).format('YYYY-MM-DD HH:mm:ss') }} </p>
        </div>
    </div>
    {% endfor %}
</div><!--/.articles-->

<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    {% block sidebar %}
        <div class="sidebar-module sidebar-module-inset">
            <h4>个人说明</h4>
                <p>本网站为印第安酋长(小猛)个人博客</p>
        </div>
        <div class="sidebar-module">
            <h4>相关链接</h4>
                <ol class="list-unstyled">
                    <li><a href="https://github.com/">GitHub</a></li>
                    <li><a href="http://www.lnts.com.cn/">鲁能泰山官方网站</a></li>
                    <li><a href="http://www.zhibo8.cc/index.html">直播8</a></li>
                </ol>
        </div>
        <div class="sidebar-module">
            <div id="cyReping" role="cylabs" data-use="reping"></div>
            </div>
        {% endblock %}
</div><!-- /.blog-sidebar -->

</div><!--/.row-->

<div class="col-lg-offset-5 col-sm-offset-5">
    {{ macros.pagination_widget(pagination,'.index') }}
</div>

{% endblock %}



{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/item.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}
{% block title %}印第安酋长{% endblock %}
{% block page_image %}
    <div class="container-fluid">
        <div class="row">
            <div class="image_header col-lg-12" style="height: 400px;background-image: url('http://imgsrc.baidu.com/forum/pic/item/902397dda144ad345d1edb20d0a20cf430ad85f7.jpg')">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="page_title">
                            {% for article in articles %}
                                <h4 style="line-height: 300px;"><span style="font-size:35px;" class="glyphicon glyphicon-tag"></span> {{ article.item.tag }}</h4>
                            {% endfor %}
                        </div>
                    </div>
            </div>
        </div>
    <div>
{% endblock %}
{% block page_content %}
<ul class="articles">
    {% for article in articles %}
    <div class="article">
        <div class="article_title">
            <a href="{{ url_for('.article',id=article.id) }}">
                <h5><span class="glyphicon glyphicon-link"></span> {{ article.title }}</h5>
            </a>
        </div>
        <a href="{{ url_for('.article',id=article.id) }}">
            <div class="article-body">
                {% if article.body_html %}
                    {{ article.body_html | safe | truncate(200,  killwords=False, end='...') }}

                {% endif %}
            </div>
        </a>

        <div class="row">
            <a class="col-lg-2 col-sm-2 col-xs-2 article_tag" href="{{ url_for('.item',tag = article.item.tag) }}">
                <span class="label label-info">
                {{ article.item.tag }}
                </span>
            </a>
            <p class="col-lg-3 col-sm-3 col-xs-7 col-xs-offset-5 col-sm-offset-9 col-lg-offset-9 article_time">{{ moment(article.timestamp).format('YYYY-MM-DD HH:mm:ss') }} </p>
        </div>


        <hr />

    </div>
    {% endfor %}
</ul>

{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/publish.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}发布文章{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>主人，您想写点啥？</h1>
</div>
<div class="col-md-10">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/upload.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}上传文件{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>已经上传的文件</h1>
    {% for filename in filelist%}
        <a href="{{ url_for('.download',filename=filename) }}">
            {{filename}}
        </a>
        <br/>
    {% endfor %}
</div>
<hr/>
{% if current_user.is_authenticated %}
<div class="page-header">
    <h1>主人，您想上传点啥？</h1>
</div>
<div class="col-md-10">
    {{ wtf.quick_form(form) }}
</div>
{% endif %}
{% endblock %}